// Run explicitly when replacing the fixed proof assets; checks never rewrite hashes.
const fs = require('node:fs');
const crypto = require('node:crypto');
const root = 'assets/maps/north-finchley';
const paths = ['basemap.pmtiles', ...Array.from({ length: 256 }, (_, i) => `fonts/Noto Sans Regular/${i * 256}-${i * 256 + 255}.pbf`)];
const files = paths.map(path => {
  const bytes = fs.readFileSync(`${root}/${path}`);
  return { path, bytes: bytes.length, md5: crypto.createHash('md5').update(bytes).digest('hex'), sha256: crypto.createHash('sha256').update(bytes).digest('hex') };
});
const revision = crypto.createHash('sha256').update(JSON.stringify(files)).digest('hex').slice(0, 16);
fs.mkdirSync('src/map', { recursive: true });
fs.writeFileSync('src/map/catalog.json', JSON.stringify({
  id: `north-finchley-${revision}`, bounds: [-0.196, 51.600, -0.159, 51.626], minTileZoom: 0, maxTileZoom: 15,
  source: 'https://build.protomaps.com/20260915.pmtiles', tilesetVersion: '4.15.2',
  fontCommit: '028c18f713baecad011301ff7a69acc39bcc2ae7', files,
}, null, 2) + '\n');
fs.writeFileSync('src/map/bundledAssets.ts', '// Generated by tools/maps/catalog.cjs. Static requires let Metro embed every resource.\n/* eslint-disable @typescript-eslint/no-require-imports */\nexport const bundledMapAssets: Record<string, number> = {\n' + paths.map(path => `  ${JSON.stringify(path)}: require(${JSON.stringify(`../../${root}/${path}`)}),`).join('\n') + '\n};\n');
console.log(`${files.length} files, ${files.reduce((n, f) => n + f.bytes, 0)} bytes, ${revision}`);
fs.writeFileSync('src/map/notices.json', JSON.stringify({
  attribution: 'Map data © OpenStreetMap contributors, available under the Open Database Licence (ODbL) 1.0: https://www.openstreetmap.org/copyright and https://opendatacommons.org/licenses/odbl/1-0/ . Basemap extract from Protomaps, 15 September 2026, tileset 4.15.2. Natural Earth data is public domain. The archive also contains unused ESA WorldCover landcover data, © ESA WorldCover project 2021, CC BY 4.0: https://creativecommons.org/licenses/by/4.0/ . This local style does not display that landcover layer. Rendered with MapLibre Native (BSD 2-Clause) / MapLibre React Native (MIT). Fonts: Noto Sans Regular, SIL Open Font License 1.1 below. No sprite or downloaded icons are used. Public map data is not a field access or safety assessment.',
  fontLicense: fs.readFileSync(`${root}/FONT-LICENSE.txt`, 'utf8'),
  rendererLicenses: ['MAPLIBRE-RN-LICENSE.txt', 'MAPLIBRE-NATIVE-LICENSE.txt'].map(name => `${name}\n${fs.readFileSync(`${root}/${name}`, 'utf8')}`).join('\n\n'),
}, null, 2) + '\n');
